name: Build Docker images and push to Artifact Registry

on: [push, pull_request]

env:
  GCP_PROJECT: tonxdao-dev
  REGION: asia-south1
  REPOSITORY: asia-south1-docker.pkg.dev/tonxdao-dev/tonxdao

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: asia-south1-docker.pkg.dev/tonxdao-dev/tonxdao/xdao-frontend
            directory: .

    steps:
      - name: checkout
        uses: 'actions/checkout@v4'

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Setup Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Docker login
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build image
        working-directory: ${{ matrix.directory }}
        run: |-
          docker build . --tag ${{ matrix.image }}:${{ github.sha }}
          if [ ${{ steps.extract_branch.outputs.branch }} == "main" ]; then
            docker tag ${{ matrix.image }}:${{ github.sha }} ${{ matrix.image }}:latest
          fi

      - name: Push image
        run: docker push ${{ matrix.image }} --all-tags
